<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ClrLens.IL</AssemblyName>
    <RootNamespace>ClrLens.IL</RootNamespace>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../ClrLens.Core/ClrLens.Core.csproj" /></ItemGroup>
</Project>
