<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ClrLens.Tests.IL</AssemblyName>
    <RootNamespace>ClrLens.Tests.IL</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ClrLens.PE/ClrLens.PE.csproj" />
    <ProjectReference Include="../../src/ClrLens.IL/ClrLens.IL.csproj" />
    <ProjectReference Include="../../src/ClrLens.IR/ClrLens.IR.csproj" />
    <ProjectReference Include="../../src/ClrLens.Analysis/ClrLens.Analysis.csproj" />
    <ProjectReference Include="../fixtures/ClrLens.SampleFixtures/ClrLens.SampleFixtures.csproj" />
  </ItemGroup>
</Project>
