<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ClrLens.Tests.Unit</AssemblyName>
    <RootNamespace>ClrLens.Tests.Unit</RootNamespace>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CS1591;CA1707;CA1305</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <ProjectReference Include="../../src/ClrLens.Core/ClrLens.Core.csproj" />
    <ProjectReference Include="../../src/ClrLens.PE/ClrLens.PE.csproj" />
    <ProjectReference Include="../../src/ClrLens.IL/ClrLens.IL.csproj" />
    <ProjectReference Include="../../src/ClrLens.IR/ClrLens.IR.csproj" />
    <ProjectReference Include="../../src/ClrLens.Analysis/ClrLens.Analysis.csproj" />
    <ProjectReference Include="../../src/ClrLens.Rules/ClrLens.Rules.csproj" />
    <ProjectReference Include="../../src/ClrLens.Reporting/ClrLens.Reporting.csproj" />
    <ProjectReference Include="../fixtures/ClrLens.SampleFixtures/ClrLens.SampleFixtures.csproj" />
  </ItemGroup>
</Project>
